### ISSUE TITLE
PFBlockBuilder

### ISSUE THREAD

**Issue by cbernet** [HEP-FCC/papas#11]
https://github.com/HEP-FCC/papas/blob/master/papas/reconstruction/src/PFBlockBuilder.cpp#L16 use a template method? this method would collect the set of ids of a given collection. actually why not give collectionIds the typeAndSubtype? first template getCollection. 

in getCollectionIds, loop might not be necessary.

container of ids should probably be a set (collectionIds should return a set?)

then combine the sets (tracks or ecals or hcals) -- if staying with the current logic. 

could also test only the links we want to test:
- tracks-ecals
- tracks-hcals
- ecals-hcals (?)

**Comment by cbernet** [comment]
Beware of the sets w/r to sorting

**Comment by alicerobson** [comment]
Done, issue needs to be closed.
