### ISSUE TITLE
Turn builders into functions

### ISSUE THREAD

**Issue by cbernet** [HEP-FCC/papas#13]
If there is no attribute, no need to have a class. 
For example, the MergedClusterBuilder does not seem to need its two attributes, merged and history, which are references to external objects. 

Same for PFBlockBuilder

proposed names: 

build_pfblocks, merge_clusters,  (in the papas namespace).

Need to check python and create a similar issue there.

**Comment by cbernet** [comment]
What about GraphBuilder? turn to a subgraphs function?

**Comment by alicerobson** [comment]
Done, issue needs to be closed.
