### ISSUE TITLE
review constructor calls and the use of auto

### ISSUE THREAD

**Issue by cbernet** [HEP-FCC/papas#14]
when constructing an object on the stack: 

    Class object( args );

instead of 

    auto obj = Class (args);

Grep with: 

    grep -r auto . --include='*.cpp' | grep -v \\\\&

Native types: 

    bool found=false; 

instead of 

    auto found = false

Should there be a & after auto or not? 

    auto foo = get_bar()

if get_bar() returns a const ref, then I think that a copy is done to create foo. 
Maybe what we want is 

    auto& foo = get_bar() 

in which case auto plays the role of const whatever

or even? 

    const auto& = get_bar() 

Before C++ 11, could do the following 2 things (different behaviour, a copy is done in the second case)

    const Foo& foo = get_bar()
  
    Foo foo = get_bar()

**Comment by jlingema** [comment]
If `get_bar()` returns `const Foo&`, you'll need `const auto&`, since `auto` only derives the type and indeed will lead to copies if you use `auto foo = get_bar()` or `auto& foo = get_bar()`

**Comment by alicerobson** [comment]
now merged
